name: Godot Android Export

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    name: Build Godot APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile Game to APK
        uses: firebelley/godot-export@v6.0.0
        with:
          godot-version: 4.3
          godot-export-preset: Android
          create-release: false
